### PR TITLE
Main5 map

### PR DESCRIPTION
**Pull request by mschumacher3**
Labels move. They are not positioned correctly, and the content is not
accurate, has the state, not the data. They do remove when mouse out.

### CODE REVIEW

**Comment by amandelman** [comment]
Hey, Molly. This pull request has conflicts. I'm going to pull down your branch and take a look to try and resolve them. That cool?

**Comment by mschumacher3** [comment]
That's fine! I was trying to see how to resolve it, but i'm not sure how to take a look at it.

**Comment by amandelman** [comment]
All taken care of! I don't see the labels yet, but that's ok. I did notice some funky stuff with the CSS in other spots on the page (Washington, NY). I'm not sure if that was from this latest pull request, but I'm going to try and fix that.

**Comment by mschumacher3** [comment]
Thanks! I see that too.. Oh no. They were working right before I committed it. I will look into it

Sent from Outlook Mobilehttps://aka.ms/qtex0l

On Wed, May 4, 2016 at 8:54 PM -0700, "amandelman" <notifications@github.com<mailto:notifications@github.com>> wrote:

All taken care of! I don't see the labels yet, but that's ok. I did notice some funky stuff with the CSS in other spots on the page (Washington, NY). I'm not sure if that was from this latest pull request, but I'm going to try and fix that.

##

**Pull request merged**
