### PR TITLE
California mapping

### PR DESCRIPTION
**Pull request by emullendore**

### CODE REVIEW

**Comment by amandelman** [comment]
Looks like my texts are all janky, so we can try and figure this out here. As far as I can tell you're right about the conflicts being in index.html. At first I was worried about a bunch of changes in the "other pppl's work commit," but maybe that's not an issue? Do you know what happened there?)

Anyway, which lines in index.html look to be the problem? If it's just a matter of overwriting some scripts I loaded, I can re-do that pretty easily.

**Comment by emullendore** [comment]
I mean, your scripts should be fine. I merged them earlier today and I thought I synced the main branch with my branch. I moved my california div around and added more divs for selecting map layers (still unsuccessful)

**Comment by emullendore** [comment]
if worse comes to worse, I could manually add my california stuff and change index.html,  we just make sure everyone knows about the changes in the index and is merged into their respective branches, right?

**Comment by amandelman** [comment]
Is it possible that line 11 in index.html is the problem? There's a second stylesheet declaration (duplicated from line 13). It's possible you don't want to sync the main branch with your branch until their merged, so maybe something happened there? Anyway. Go out with your friend and we can figure it out tomorrow. Also, my buddy at Github can take a look and advise if we need help.

**Comment by emullendore** [comment]
I think you're right about that

**Comment by emullendore** [comment]
OK How about since most of these problems are due to my california files, I just remove and re-add my files? The lesson here is that I probably shouldn't have made so many changes before finally deciding to commit to master.

**Comment by amandelman** [comment]
You could try that. I don't think the number of commits is the issue. Is it possible you synced your branch _from_ the master at some point along the way before then trying to merge it back into the master? I think that could conflicts outside your California files because Git will try to merge two different instances of the master (it's current state and the state in your branch from when you synced). Does that make sense? 

Either way, your solution sounds like it could work. I'm just trying to figure out what happened. If you want my friend at GitHub to take a look, lemme know.

**Comment by emullendore** [comment]
Ok. I'm going to go ahead and do that. And you are correct about syncing
with master. This is a learning process to say the least. At least this did
not negatively impact anyone's progress, besides my own

**Pull request closed without merging**
